import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import StoreProvider from "@/app/store-provider"
import { HeroUIProvider } from "@heroui/react"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeroUIProvider>
          <StoreProvider>{children}</StoreProvider>
        </HeroUIProvider>
      </body>
    </html>
  )
}
